# Generated by Django 3.1.7 on 2021-05-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210531_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggeraccount',
            name='blogname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
