# Generated by Django 3.1.7 on 2021-06-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210601_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel1',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel2',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel3',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel4',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel5',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel6',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel7',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='corousel8',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='bloggeraccount',
            name='template',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel1',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel2',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel3',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel4',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel5',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel6',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel7',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='corousel8',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='subscription_active',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='subscripton_amount',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='template',
        ),
    ]
