# Generated by Django 3.2 on 2021-07-23 12:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210619_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraccount',
            name='adhar_card',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='adhar_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='bank_account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='bank_ifsc_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='pan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='pan_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='vat',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
