# Generated by Django 3.2 on 2021-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210723_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendoraccount',
            name='shop_name',
            field=models.CharField(max_length=150),
        ),
    ]
