# Generated by Django 3.2 on 2021-07-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_vendoraccount_shop_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='is_blocked',
            new_name='is_verified',
        ),
    ]
