# Generated by Django 3.2 on 2021-08-21 09:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_is_blocked_vendoraccount_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraccount',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_uplaod_file_name),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='pinterest',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='vision',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='vendoraccount',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
