# Generated by Django 3.2 on 2021-08-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210821_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='adhar_card',
            new_name='aadhaar_card',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='adhar_image',
            new_name='aadhaar_image',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='facebook',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='instagram',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='linkedin',
            new_name='linkedin_link',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='pinterest',
            new_name='pinterest_link',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='twitter',
            new_name='twitter_link',
        ),
        migrations.RenameField(
            model_name='vendoraccount',
            old_name='youtube',
            new_name='youtube_link',
        ),
    ]
