# Generated by Django 3.2 on 2021-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210821_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendoraccount',
            name='pinterest_link',
        ),
        migrations.RemoveField(
            model_name='vendoraccount',
            name='vision',
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendoraccount',
            name='shop_add',
            field=models.CharField(max_length=200),
        ),
    ]
