# Generated by Django 3.1.7 on 2021-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('message', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('contact_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
