# Generated by Django 3.1.7 on 2021-05-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
    ]
